[theme]
primaryColor = "#22C55E"  # Lime green for action buttons (Duolingo-inspired)
backgroundColor = "#FFFFFF"  # Clean white background
secondaryBackgroundColor = "#F9FAFB"  # Soft off-white for cards
textColor = "#1F2937"  # Cool dark blue-gray
font = "sans serif"  # Keep modern and friendly

[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false

[logger]
level = "error"